<?php $helper = Mage::helper('cookiecompliance'); ?>
<?php if($helper->isEnable()){ ?>
    <div class="cc-window -with-attributes" data-background-color="<?php echo($helper->getBgColor()); ?>"
         data-text-color="<?php echo($helper->getTextColor()); ?>"
         data-btn-background-color="<?php echo($helper->getBtnBgColor()); ?>"
         data-btn-text-color="<?php echo($helper->getBtnColor()); ?>"
         data-message-text="<?php echo $helper->getMsg(); ?>"
         data-position="<?php echo $helper->getPosition(); ?>"></div>
<?php } ?>

<?php if($helper->isGoogleEnable()){ ?>
    <!-- Google Analytics Code -->
    <script id="google-analytics-code">
        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
            (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
        ga('create', '<?php echo $helper->getGoogleId(); ?>', 'auto');ga('send', 'pageview');
    </script>
    <!-- Google Analytics Code -->
<?php } ?>

<?php if($helper->isFacebookEnable()){ ?>
    <!-- Facebook Pixel Code -->
    <script id="facebook-pixel">
        !function(f,b,e,v,n,t,s)
        {if(f.fbq)return;n=f.fbq=function(){n.callMethod?
            n.callMethod.apply(n,arguments):n.queue.push(arguments)};
            if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';
            n.queue=[];t=b.createElement(e);t.async=!0;
            t.src=v;s=b.getElementsByTagName(e)[0];
            s.parentNode.insertBefore(t,s)}(window, document,'script',
            'https://connect.facebook.net/en_US/fbevents.js');
        fbq('init', '<?php echo $helper->getFacebookId(); ?>');
        fbq('track', 'PageView');
    </script>
    <noscript><img height="1" width="1" style="display:none"
                   src="https://www.facebook.com/tr?id=<?php echo $helper->getFacebookId(); ?>&ev=PageView&noscript=1"
        /></noscript>
    <!-- End Facebook Pixel Code -->
<?php } ?>
