<?php $helper = Mage::helper('cookiecompliance'); ?>
<?php if($helper->isEnable()){ ?>
<div class="class="cc-window"></div>
<?php } ?>
<?php if(isset($_COOKIE['cookieconsent_status']) && $_COOKIE['cookieconsent_status'] == "allow"){ ?>
		<?php if($helper->isGoogleEnable()){ ?>
				<!-- Google Analytics Code -->
				<script>
				  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
				  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
				  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
				  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
	
				  ga('create', '<?php echo $helper->getGoogleId(); ?>', 'auto');ga('send', 'pageview');
				</script>
				<!-- Google Analytics Code -->
		<?php } ?>	
		
		<?php if($helper->isFacebookEnable()){ ?>
			
				<!-- Facebook Pixel Code -->
				<script>
				  !function(f,b,e,v,n,t,s)
				  {if(f.fbq)return;n=f.fbq=function(){n.callMethod?
				  n.callMethod.apply(n,arguments):n.queue.push(arguments)};
				  if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';
				  n.queue=[];t=b.createElement(e);t.async=!0;
				  t.src=v;s=b.getElementsByTagName(e)[0];
				  s.parentNode.insertBefore(t,s)}(window, document,'script',
				  'https://connect.facebook.net/en_US/fbevents.js');
				  fbq('init', '<?php echo $helper->getFacebookId(); ?>');
				  fbq('track', 'PageView');
				</script>
				<noscript><img height="1" width="1" style="display:none"
				  src="https://www.facebook.com/tr?id=<?php echo $helper->getFacebookId(); ?>&ev=PageView&noscript=1"
				/></noscript>
				<!-- End Facebook Pixel Code -->
		<?php } ?>	
	<?php } ?>		

<script>
    <?php if( !isset($_COOKIE['cookieconsent_status']) || $_COOKIE['cookieconsent_status'] == ""){ ?>
  var p;
 cookieconsent.initialise({
    type: 'opt-in',
	palette: {
      "popup":{"background":"<?php echo ($helper->getBgColor()); ?>","text":"<?php echo ($helper->getTextColor()); ?>", },
      "button":{"background":"<?php echo ($helper->getBtnBgColor()); ?>","text":"<?php echo ($helper->getBtnColor()); ?>"},
    },
	content: {
		  header: 'Cookies used on the website!',
		  message: '<?php echo $helper->getMsg(); ?>',
		  dismiss: 'Deny',
		  allow: 'Allow cookies',
		  deny: 'Decline',
          link: '',
	},
	position: '<?php echo $helper->getPosition(); ?>',
	onStatusChange: function(status) {
    	if(status==="allow")
		{
			location.reload();
		}

    },
    
   },function (popup) {
   		p = popup;
   }, function (err) {
     //console.error(err);
   });
<?php } ?>
jQuery(document).load(function(e) {
 if(browsercookie.cookieconsent_status="")
   	 p.open();
});

</script>
