<?php $helper = Mage::helper('cookiecompliance'); ?>
<?php if($helper->isEnable()){ ?>
    <div class="cc-window -with-attributes" data-background-color="<?php echo($helper->getBgColor()); ?>"
         data-text-color="<?php echo($helper->getTextColor()); ?>"
         data-btn-background-color="<?php echo($helper->getBtnBgColor()); ?>"
         data-btn-text-color="<?php echo($helper->getBtnColor()); ?>"
         data-message-text="<?php echo htmlentities($helper->getMsg()); ?>"
         data-more-info-link="<?php echo $helper->getLink(); ?>"
         data-position="<?php echo $helper->getPosition(); ?>"></div>
<?php } ?>
